# Base configuration that will be shared across different
# Build environments

# Make sure DB Port is not in conflict
# Spent hours trying to make it work before realizing
# the port was already taken by other instance of postgres :(

application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name : "newsletter"